-- ============================================================================
--  BUILD WITH US  —  materials, contractors, designs & designers
--  Run this ONCE in the Supabase SQL editor (project ioblbfugnhtghvxbyeos).
--  Creates + seeds the four catalogs the consumer "Build With Us" page and the
--  admin panel share, with permissive RLS (matching the other tables).
--
--  NOTE: columns the JS reads in camelCase ("priceUnit", "priceFrom") are quoted
--  so PostgREST returns them with the exact key the app expects. Array fields
--  (tags / styles / scope / portfolio / types) are jsonb.
--
--  The consumer site shows the static bundled catalog until a table has rows;
--  once seeded here, admin edits persist and surface on the live site.
-- ============================================================================
SET search_path = public;
DO $img$ BEGIN END $img$;  -- no-op marker

-- helper note: image base = https://images.unsplash.com/photo-<id>?w=600&h=400&fit=crop

-- ───────────────────────── Materials & Hardware ─────────────────────────
CREATE TABLE IF NOT EXISTS public.build_materials (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  category    text,
  brand       text,
  supplier    text,
  unit        text,
  price       numeric,
  stock       text,
  image       text,
  description text,
  types       jsonb,
  created_at  timestamptz DEFAULT now()
);

INSERT INTO public.build_materials (id, name, category, brand, supplier, unit, price, stock, image, types, description) VALUES
 (1,'UltraTech Cement OPC 53 Grade','Cement','UltraTech','BuildMart Gurgaon','50kg bag',410,'In Stock','https://images.unsplash.com/photo-1575493438282-4e0fb32d1bdd?w=600&h=400&fit=crop','["Residential","Commercial","Industrial"]','High-strength OPC for RCC & structural work.'),
 (2,'TATA Tiscon 550SD TMT Bars (12mm)','Steel & TMT','TATA Steel','Steel Hub Sohna Rd','per ton',62500,'In Stock','https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=600&h=400&fit=crop','["Residential","Commercial","Industrial"]','Earthquake-resistant Fe-550 TMT rebars.'),
 (3,'AAC Lightweight Blocks (600x200x100)','Bricks & Blocks','Magicrete','New Gurgaon Depot','per block',48,'In Stock','https://images.unsplash.com/photo-1531685250784-7569952593d2?w=600&h=400&fit=crop','["Residential","Commercial","Renovation"]','Autoclaved aerated concrete — light & insulating.'),
 (4,'Kajaria Vitrified Floor Tiles (600x600)','Tiles & Flooring','Kajaria','Tile Studio DLF','per box (4)',1180,'Low Stock','https://images.unsplash.com/photo-1678742755904-6c3fc8ba6602?w=600&h=400&fit=crop','["Residential","Commercial","Renovation","Interiors"]','Double-charge vitrified tiles, matt finish.'),
 (5,'Asian Paints Royale Luxury Emulsion','Paints','Asian Paints','ColorWorld SPR','20L bucket',7600,'In Stock','https://images.unsplash.com/photo-1623944361530-8a6cd3eb0de8?w=600&h=400&fit=crop','["Residential","Renovation","Interiors"]','Premium washable interior emulsion.'),
 (6,'Astral CPVC Pipes & Fittings Set','Plumbing','Astral','AquaFit Traders','set',3400,'In Stock','https://images.unsplash.com/photo-1646009445351-b8192e095f3a?w=600&h=400&fit=crop','["Residential","Commercial","Renovation"]','Lead-free hot & cold water CPVC system.'),
 (7,'Havells Modular Switches & MCB Kit','Electrical','Havells','Voltline Gurgaon','kit',5200,'In Stock','https://images.unsplash.com/photo-1781243680870-6d33bf6874c1?w=600&h=400&fit=crop','["Residential","Commercial","Renovation"]','Complete switchgear + modular plates.'),
 (8,'Hindware Wall-Hung WC + Cistern','Sanitaryware','Hindware','Bath Gallery','piece',9800,'Out of Stock','https://images.unsplash.com/photo-1587527901949-ab0341697c1e?w=600&h=400&fit=crop','["Residential","Renovation","Interiors"]','Rimless wall-hung toilet with soft-close.'),
 (9,'Fevicol Marine Plywood (19mm BWP)','Wood & Ply','Century','Timber Mart','per sheet',4200,'In Stock','https://images.unsplash.com/photo-1611072337226-1140ab367200?w=600&h=400&fit=crop','["Residential","Renovation","Interiors"]','Boiling-water-proof plywood for kitchens & wardrobes.'),
 (10,'Saint-Gobain Toughened Glass (12mm)','Glass & Aluminium','Saint-Gobain','GlassLine NCR','per sq.ft',320,'In Stock','https://images.unsplash.com/photo-1523477593243-78bbf626fd3b?w=600&h=400&fit=crop','["Residential","Commercial","Interiors"]','Tempered safety glass for façades & railings.'),
 (11,'Godrej Door Hardware & Locks Set','Hardware & Fittings','Godrej','FitWell Hardware','set',2850,'In Stock','https://images.unsplash.com/photo-1583691028182-e8f01e74bfa2?w=600&h=400&fit=crop','["Residential","Commercial","Renovation","Interiors"]','Mortise locks, handles & hinges (SS304).'),
 (12,'Red Clay Bricks (Class-A)','Bricks & Blocks','Local Kiln','New Gurgaon Depot','per 1000',8500,'In Stock','https://images.unsplash.com/photo-1605296862588-2858174c3e6e?w=600&h=400&fit=crop','["Residential","Commercial","Industrial"]','Kiln-fired first-class bricks for masonry.'),
 (13,'Fire-Rated Steel Door (90-min)','Hardware & Fittings','Shakti Hormann','SafeBuild Systems','piece',28500,'In Stock','https://images.unsplash.com/photo-1583691028182-e8f01e74bfa2?w=600&h=400&fit=crop','["Commercial","Industrial"]','BS-476 certified fire door for offices & warehouses.'),
 (14,'Heavy-Duty Industrial Vitrified Tiles','Tiles & Flooring','Simpolo','Tile Studio DLF','per box (4)',1650,'In Stock','https://images.unsplash.com/photo-1678742755904-6c3fc8ba6602?w=600&h=400&fit=crop','["Commercial","Industrial"]','High-abrasion full-body tiles for high-footfall floors.'),
 (15,'Epoxy Industrial Floor Coating','Paints','Sika','IndCoat Solutions','20kg pack',9400,'In Stock','https://images.unsplash.com/photo-1623944361530-8a6cd3eb0de8?w=600&h=400&fit=crop','["Industrial","Commercial"]','Seamless, chemical-resistant epoxy for factory floors.'),
 (16,'Structural ISMB Steel Beams','Steel & TMT','SAIL','Steel Hub Sohna Rd','per ton',71000,'In Stock','https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=600&h=400&fit=crop','["Industrial","Commercial"]','Hot-rolled I-beams for PEB & structural frames.'),
 (17,'Italian Marble Slabs (Statuario)','Tiles & Flooring','Imported','Stone Gallery','per sq.ft',850,'Low Stock','https://images.unsplash.com/photo-1678742755904-6c3fc8ba6602?w=600&h=400&fit=crop','["Interiors","Residential"]','Luxury white Italian marble for living & lobbies.'),
 (18,'Greenlam Designer Laminates (Hi-Gloss)','Wood & Ply','Greenlam','Timber Mart','per sheet',2100,'In Stock','https://images.unsplash.com/photo-1611072337226-1140ab367200?w=600&h=400&fit=crop','["Interiors","Residential"]','Designer laminates for wardrobes & modular kitchens.')
ON CONFLICT (id) DO NOTHING;

-- ───────────────────────── Contractors & Services ─────────────────────────
CREATE TABLE IF NOT EXISTS public.build_services (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  profession     text,
  specialization text,
  experience     text,
  rating         numeric,
  projects       integer,
  location       text,
  avatar         text,
  price          text,
  "priceUnit"    text,
  verified       boolean DEFAULT true,
  tags           jsonb,
  created_at     timestamptz DEFAULT now()
);

INSERT INTO public.build_services (id, name, profession, specialization, experience, rating, projects, location, avatar, price, "priceUnit", verified, tags) VALUES
 (1,'Rajesh Kumar Constructions','Civil Contractor','RCC, structural & turnkey residential builds','18 yrs',4.9,240,'Sector 65, Gurgaon','https://i.pravatar.cc/150?img=12','₹1,650','per sq.ft',true,'["RCC","Turnkey","Residential"]'),
 (2,'Ar. Sneha Malhotra','Architect','Modern & sustainable residential / commercial design','12 yrs',4.8,95,'DLF Phase 5','https://i.pravatar.cc/150?img=47','₹120','per sq.ft',true,'["Modern","Sustainable","3D Design"]'),
 (3,'Priya Interiors Studio','Interior Designer','Luxury homes, modular kitchens & wardrobes','10 yrs',4.9,130,'Golf Course Road','https://i.pravatar.cc/150?img=45','₹1,500','per sq.ft',true,'["Modular Kitchen","Wardrobes","Luxury"]'),
 (4,'Eng. Vikram Singh','Structural Engineer','High-rise RCC, steel & PEB structural design','15 yrs',4.7,60,'Sector 49, SPR','https://i.pravatar.cc/150?img=52','₹15','per sq.ft',true,'["RCC","Steel","PEB"]'),
 (5,'PowerFlow MEP Consultants','MEP Consultant','Electrical, plumbing & HVAC design + execution','14 yrs',4.6,80,'Udyog Vihar','https://i.pravatar.cc/150?img=33','₹40','per sq.ft',true,'["HVAC","Electrical","Plumbing"]'),
 (6,'GreenScape Landscape Studio','Landscape Designer','Gardens, terraces & vertical greens','9 yrs',4.8,70,'New Gurgaon','https://i.pravatar.cc/150?img=23','₹250','per sq.ft',true,'["Terrace Garden","Vertical Green","Irrigation"]'),
 (7,'Acharya R. Sharma','Vastu Consultant','Residential & commercial Vastu analysis','20 yrs',4.9,500,'Gurgaon','https://i.pravatar.cc/150?img=68','₹11,000','per consult',true,'["Vastu","Residential","Commercial"]'),
 (8,'BuildRight Turnkey','Turnkey Builder','End-to-end construction, design to handover','16 yrs',4.8,110,'Sohna Road','https://i.pravatar.cc/150?img=60','₹1,850','per sq.ft',true,'["Turnkey","Residential","Commercial"]'),
 (9,'Ar. Karan Mehta','Architect','Contemporary villas & interior architecture','8 yrs',4.7,55,'Sector 71, SPR','https://i.pravatar.cc/150?img=55','₹100','per sq.ft',false,'["Contemporary","Villas","Interiors"]'),
 (10,'FixIt Renovations','Renovation Contractor','Home renovation, waterproofing & painting','11 yrs',4.6,320,'Gurgaon','https://i.pravatar.cc/150?img=14','₹800','per sq.ft',true,'["Renovation","Waterproofing","Painting"]')
ON CONFLICT (id) DO NOTHING;

-- ───────────────────────── Design Ideas (interior & exterior) ─────────────────────────
CREATE TABLE IF NOT EXISTS public.build_designs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  scope       text,           -- Interior | Exterior
  zone        text,
  style       text,
  designer    text,
  rating      numeric,
  "priceFrom" numeric,
  "priceUnit" text,
  timeline    text,
  image       text,
  description text,
  tags        jsonb,
  created_at  timestamptz DEFAULT now()
);

INSERT INTO public.build_designs (id, title, scope, zone, style, designer, rating, "priceFrom", "priceUnit", timeline, image, tags, description) VALUES
 (1,'Modern Living Room','Interior','Living Room','Modern','Priya Interiors Studio',4.9,85000,'per room','3–4 weeks','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop','["Modern","Minimal","Accent Decor"]','Warm minimalist living room with statement accent chair, gallery art & layered lighting.'),
 (2,'Open-Plan Living & Dining','Interior','Living Room','Contemporary','Ar. Karan Mehta',4.7,120000,'per room','4–5 weeks','https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop','["Contemporary","Open-Plan","Space-Saving"]','Space-smart open layout merging kitchen, dining & lounge for compact homes.'),
 (3,'Luxury Master Bedroom','Interior','Bedroom','Luxury','Priya Interiors Studio',4.9,110000,'per room','4–5 weeks','https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&h=400&fit=crop','["Luxury","Statement Wall","Cozy"]','Dark statement wall, upholstered bed, designer chandelier & city-view drapery.'),
 (4,'Coastal Living Room','Interior','Living Room','Coastal','Ar. Sneha Malhotra',4.8,95000,'per room','3–4 weeks','https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&h=400&fit=crop','["Coastal","Bright","Relaxed"]','Bright, breezy living room with blue accents, natural light & relaxed textures.'),
 (5,'Minimal Modular Kitchen','Interior','Kitchen','Minimalist','Priya Interiors Studio',4.9,180000,'per kitchen','5–6 weeks','https://images.unsplash.com/photo-1556911220-bff31c812dba?w=600&h=400&fit=crop','["Modular","Marble","Handle-less"]','Handle-less white modular kitchen with marble counters & built-in appliances.'),
 (6,'Classic Island Kitchen','Interior','Kitchen','Classic','Priya Interiors Studio',4.8,165000,'per kitchen','5–6 weeks','https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=600&h=400&fit=crop','["Modular","Island","Hex Tile"]','Shaker cabinetry, wood-clad island, hex backsplash & breakfast seating.'),
 (7,'Spa Bathroom','Interior','Bathroom','Spa','Ar. Karan Mehta',4.7,95000,'per bath','3–4 weeks','https://images.unsplash.com/photo-1620626011761-996317b8d101?w=600&h=400&fit=crop','["Spa","Freestanding Tub","Premium"]','Freestanding soaking tub, vessel basin & calm neutral palette with greenery.'),
 (8,'Modern Bathroom','Interior','Bathroom','Modern','Priya Interiors Studio',4.8,80000,'per bath','3–4 weeks','https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop','["Modern","Walk-in Shower","Vanity"]','Walk-in glass shower, double vanity & warm wood-tone flooring.'),
 (9,'Modern House Facade','Exterior','Facade','Modern','Ar. Sneha Malhotra',4.8,150,'per sq.ft','6–8 weeks','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop','["Facade","Glass","Wood Cladding"]','Contemporary elevation in timber cladding, full-height glazing & dusk lighting.'),
 (10,'Pool & Landscape','Exterior','Landscape','Contemporary','GreenScape Landscape Studio',4.8,320,'per sq.ft','6–8 weeks','https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop','["Pool","Garden","Outdoor"]','Resort-style backyard with pool deck, tropical planting & outdoor lounge.'),
 (11,'Mediterranean Courtyard','Exterior','Landscape','Mediterranean','GreenScape Landscape Studio',4.8,280,'per sq.ft','7–9 weeks','https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=600&h=400&fit=crop','["Courtyard","Pool","Arches"]','Arched villa courtyard with circular pool, terracotta accents & ambient lighting.')
ON CONFLICT (id) DO NOTHING;

-- ───────────────────────── Designers (hire directory) ─────────────────────────
CREATE TABLE IF NOT EXISTS public.build_designers (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  role        text,
  scope       jsonb,
  styles      jsonb,
  experience  text,
  rating      numeric,
  projects    integer,
  location    text,
  avatar      text,
  price       text,
  "priceUnit" text,
  verified    boolean DEFAULT true,
  bio         text,
  portfolio   jsonb,
  created_at  timestamptz DEFAULT now()
);

INSERT INTO public.build_designers (id, name, role, scope, styles, experience, rating, projects, location, avatar, price, "priceUnit", verified, bio, portfolio) VALUES
 (1,'Priya Interiors Studio','Interior Designer','["Interior"]','["Modern","Luxury","Minimalist"]','10 yrs',4.9,130,'Golf Course Road, Gurgaon','https://i.pravatar.cc/150?img=45','₹1,500','per sq.ft',true,'Luxury homes, modular kitchens & bespoke wardrobes with a warm minimalist signature.','["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1556911220-bff31c812dba?w=600&h=400&fit=crop"]'),
 (2,'Ar. Sneha Malhotra','Architect','["Interior","Exterior"]','["Modern","Sustainable","Coastal"]','12 yrs',4.8,95,'DLF Phase 5, Gurgaon','https://i.pravatar.cc/150?img=47','₹120','per sq.ft',true,'Modern, sustainable residential & commercial design — from facade to interiors.','["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&h=400&fit=crop"]'),
 (3,'GreenScape Landscape Studio','Landscape Designer','["Exterior"]','["Contemporary","Mediterranean","Tropical"]','9 yrs',4.8,70,'New Gurgaon','https://i.pravatar.cc/150?img=23','₹250','per sq.ft',true,'Pool decks, courtyards, terrace gardens & vertical greens for resort-style outdoors.','["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=600&h=400&fit=crop"]'),
 (4,'Studio Terra Interiors','Interior Designer','["Interior"]','["Classic","Modern","Spa"]','11 yrs',4.8,88,'Sohna Road, Gurgaon','https://i.pravatar.cc/150?img=32','₹1,300','per sq.ft',true,'Classic island kitchens, spa bathrooms & timeless living spaces with rich materials.','["https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1620626011761-996317b8d101?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop"]'),
 (5,'Ar. Karan Mehta','Architect','["Interior","Exterior"]','["Contemporary","Compact","Villas"]','8 yrs',4.7,55,'Sector 71, SPR','https://i.pravatar.cc/150?img=55','₹100','per sq.ft',false,'Contemporary villas & space-smart interior architecture for compact urban homes.','["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop"]'),
 (6,'Elevation Architects','Facade Architect','["Exterior","Interior"]','["Modern","Industrial","Glass"]','14 yrs',4.7,64,'Sector 49, Gurgaon','https://i.pravatar.cc/150?img=60','₹140','per sq.ft',true,'Striking elevations in glass, stone & timber cladding — kerb appeal that lasts.','["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop"]')
ON CONFLICT (id) DO NOTHING;

-- ───── Row-Level Security — permissive (anon read+write), matching other tables ─────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['build_materials','build_services','build_designs','build_designers'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "anon_all_%1$s" ON public.%1$I;', t);
    EXECUTE format('CREATE POLICY "anon_all_%1$s" ON public.%1$I FOR ALL USING (true) WITH CHECK (true);', t);
  END LOOP;
END $$;

-- ───── Bump identity sequences past the seeded ids so admin inserts don't collide ─────
SELECT setval(pg_get_serial_sequence('public.build_materials','id'), COALESCE((SELECT MAX(id) FROM public.build_materials), 1));
SELECT setval(pg_get_serial_sequence('public.build_services','id'),  COALESCE((SELECT MAX(id) FROM public.build_services),  1));
SELECT setval(pg_get_serial_sequence('public.build_designs','id'),   COALESCE((SELECT MAX(id) FROM public.build_designs),   1));
SELECT setval(pg_get_serial_sequence('public.build_designers','id'), COALESCE((SELECT MAX(id) FROM public.build_designers), 1));

-- Done. The consumer "Build With Us" page now reads these tables (falling back to
-- the bundled catalog if a table is empty/missing), and admin-panel edits persist.
