-- ============================================================================
--  CONNECT FRONTEND ↔ BACKEND  —  content + leads tables
--  Run this ONCE in the Supabase SQL editor (project ioblbfugnhtghvxbyeos).
--  Creates the tables the consumer site + admin panel share, seeds them with
--  the live content, and applies permissive RLS (matching the other tables).
--  After this, edits in the admin panel persist and surface on the site.
-- ============================================================================

-- ───── Website enquiries (lead funnel) ─────
CREATE TABLE IF NOT EXISTS public.leads (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref            text UNIQUE,
  intent         text DEFAULT 'contact',     -- contact | visit | callback
  status         text DEFAULT 'New',         -- New | Contacted | Visit Booked | Closed
  property_id    bigint,
  property_title text,
  name           text,
  phone          text,
  email          text,
  message        text,
  visit_date     text,
  visit_time     text,
  agent_name     text,
  created_at     timestamptz DEFAULT now()
);

-- ───── Blog posts ─────
CREATE TABLE IF NOT EXISTS public.blogs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text NOT NULL,
  excerpt    text,
  author     text,
  date       text,
  category   text,
  image      text,
  read_time  text,
  tags       text[],
  created_at timestamptz DEFAULT now()
);

-- ───── Podcasts ─────
CREATE TABLE IF NOT EXISTS public.podcasts (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        text NOT NULL,
  description  text,
  guest        text,
  guest_role   text,
  guest_avatar text,
  audio_url    text,
  video_url    text,
  poster       text,
  duration     text,
  date         text,
  listens      int DEFAULT 0,
  category     text,
  featured     boolean DEFAULT false,
  tags         text[],
  created_at   timestamptz DEFAULT now()
);

-- ───── Product videos ─────
CREATE TABLE IF NOT EXISTS public.videos (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  description text,
  video_url   text,
  thumbnail   text,
  duration    text,
  views       int DEFAULT 0,
  category    text,
  featured    boolean DEFAULT false,
  date        text,
  created_at  timestamptz DEFAULT now()
);

-- ───── Row-Level Security — permissive (anon read+write), matching other tables ─────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['leads','blogs','podcasts','videos'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "anon_all_%1$s" ON public.%1$I;', t);
    EXECUTE format('CREATE POLICY "anon_all_%1$s" ON public.%1$I FOR ALL USING (true) WITH CHECK (true);', t);
  END LOOP;
END $$;

-- ============================================================================
--  SEED — the live content (idempotent; skips rows that already exist)
-- ============================================================================
-- ===== blogs =====
INSERT INTO public.blogs (id,title,excerpt,author,date,category,image,read_time,tags) VALUES
(1,'Gurgaon New Launches 2026: 60 Projects Reshaping the Market','From DLF Privana to Trump Towers — a comprehensive guide to all 60 projects across SPR, Dwarka Expressway, Golf Course Extension, Golf Course Road, and New Gurgaon.','Rajiv Malhotra','May 24, 2026','Market Trends','https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&h=400&fit=crop','15 min read','{"Gurgaon","New Launches","2026","SPR","Dwarka Expressway"}'),
(2,'SPR vs Dwarka Expressway: Which Corridor Wins in 2026?','With DLF Privana, Elan The Statement, and Birla Estates on SPR, and Godrej Aristocrat, Emaar Urban Ascent on Dwarka Exp — we compare both corridors comprehensively.','Sanjay Khanna','May 22, 2026','Comparison','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop','10 min read','{"SPR","Dwarka Expressway","Comparison","2026"}'),
(3,'Adani Realty Enters Gurgaon: Samsara Arya & Avasa Analysed','Adani Group makes a grand residential entry into Gurgaon with two premium projects on Golf Course Extension. What this means for buyers and the market.','Priya Sharma','May 20, 2026','Developers','https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop','8 min read','{"Adani","Golf Course Ext","Samsara","New Launch"}'),
(4,'Sobha Limited in Gurgaon: Strada & Aranya — Quality Redefined','Sobha Limited launches two distinct projects — compact luxury at Sobha Strada and nature-inspired premium at Sobha Aranya. A deep dive into both offerings.','Deepak Rao','May 18, 2026','Developers','https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&h=400&fit=crop','7 min read','{"Sobha","Dwarka Exp","New Gurgaon","Strada","Aranya"}'),
(5,'First-Time Buyer Guide: New Gurgaon''s Emerging Corridors','With M3M Antalya Hills at ₹1.95 Cr, Godrej Oasis at ₹1.8 Cr, and Pyramid Urban Homes at ₹95L — New Gurgaon is the value hotspot of 2026.','Pooja Yadav','May 15, 2026','Guides','https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop','9 min read','{"First-Time Buyer","New Gurgaon","Affordable","2026"}'),
(6,'Central Park''s Double Launch: Delphine & Belanova — Resort Living Expands','Central Park launches two resort-style projects simultaneously — Delphine on Dwarka Exp and Belanova on SPR. The 5-star living concept comes to new corridors.','Amit Choudhary','May 12, 2026','New Launches','https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop','6 min read','{"Central Park","Delphine","Belanova","Resort Living"}'),
(7,'Golf Course Road: India''s Most Expensive Residential Corridor','From DLF The Camellias at ₹12 Cr to The Grove villas at ₹9.5 Cr — why Golf Course Road commands India''s highest residential prices and who buys here.','Vikas Dhawan','May 10, 2026','Market Analysis','https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop','11 min read','{"Golf Course Road","Ultra Luxury","DLF","Trump Towers"}'),
(8,'Trump Towers vs DLF Camellias: The Ultimate Luxury Showdown','Two iconic ultra-luxury addresses on Golf Course Extension — Trump Towers at ₹10 Cr and DLF Camellias at ₹12 Cr. We compare everything from floor plans to brand prestige.','Alok Srivastava','May 8, 2026','Comparison','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop','12 min read','{"Trump Towers","DLF Camellias","Ultra Luxury","Comparison"}'),
(9,'Ready-to-Move vs Under Construction: Gurgaon 2026 Guide','With DLF Arbour, Emaar Marbella, Tata Primanti, and Ireo Skyon ready to move — is it better to buy ready or invest in new launches? Our comprehensive analysis.','Sanjay Khanna','May 5, 2026','Guides','https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&h=400&fit=crop','8 min read','{"Ready to Move","Under Construction","Comparison","2026"}'),
(10,'TARC Group: The Hospitality-Backed Developer Reshaping Golf Course Ext','TARC Aayana and TARC Kailasa bring wellness-focused luxury to Golf Course Extension. How TARC''s hospitality DNA creates differentiated residential experiences.','Nandini Kapoor','May 1, 2026','Developers','https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop','7 min read','{"TARC","Golf Course Ext","Aayana","Kailasa","Luxury"}')
ON CONFLICT (id) DO NOTHING;

-- ===== podcasts =====
INSERT INTO public.podcasts (id,title,description,guest,guest_role,guest_avatar,audio_url,video_url,poster,duration,date,listens,category,featured,tags) VALUES
(1,'Golf Course Extension: India''s Most Expensive Corridor','Why Golf Course Road in Gurgaon has become the most coveted address in India — interviewing a luxury developer on ₹20+ Cr units.','Vikram Sharma, CEO - Luxury Developers Association','Real Estate Developer','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3','https://videos.pexels.com/video-files/3209828/3209828-hd_1920_1080_25fps.mp4','https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=450&fit=crop','45:32','Jun 22, 2026',8300,'market-analysis',true,'{"Golf Course","Luxury","Gurgaon"}'),
(2,'First-Time Buyer''s Guide: New Gurgaon vs. Old Gurgaon','Breaking down established Old Gurgaon vs emerging New Gurgaon — EMI planning, location and long-term appreciation.','Priya Desai, Financial Advisor','Investment Strategist','https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3','https://videos.pexels.com/video-files/2911996/2911996-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop','38:15','Jun 19, 2026',12400,'buyer-guide',true,'{"First-Time Buyer","Investment","EMI"}'),
(3,'Dwarka Expressway: The Next Real Estate Boom?','Analyzing the real estate potential of Dwarka Expressway — new launches, connectivity and why investors are betting big.','Rohit Kapoor, Real Estate Investor','Property Investor','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3','https://videos.pexels.com/video-files/7710243/7710243-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=450&fit=crop','42:08','Jun 16, 2026',9700,'market-analysis',false,'{"Dwarka Expressway","New Projects"}'),
(4,'Mortgage Myths Busted: EMI Planning & Home Loans','Clearing up misconceptions about home loans, EMI calculations and mortgage strategy.','Anita Singh, Mortgage Expert','Home Loan Specialist','https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3','https://videos.pexels.com/video-files/7578552/7578552-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop','33:42','Jun 13, 2026',7200,'finance',false,'{"Mortgage","EMI","Home Loan"}'),
(5,'3D Virtual Tours: The Future of Property Viewing','How technology — 3D tours, AI recommendations and voice-guided walkthroughs — is transforming property discovery.','Arjun Mehta, PropTech Founder','Technology Entrepreneur','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3','https://videos.pexels.com/video-files/3773486/3773486-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1558002038-1055907df827?w=800&h=450&fit=crop','39:55','Jun 10, 2026',6800,'technology',false,'{"Technology","Virtual Tours","PropTech"}'),
(6,'RERA Compliance: Protecting Your Real Estate Investment','Understanding RERA regulations, how to verify project credentials, and the protections available to homebuyers.','Sanjay Verma, Real Estate Lawyer','Legal Expert','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3','https://videos.pexels.com/video-files/5439915/5439915-hd_1920_1080_25fps.mp4','https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop','36:20','Jun 7, 2026',5400,'legal',false,'{"RERA","Legal","Compliance"}')
ON CONFLICT (id) DO NOTHING;

-- ===== videos =====
INSERT INTO public.videos (id,title,description,video_url,thumbnail,duration,views,category,featured,date) VALUES
(1,'🏢 DLF The Camellias – Ultra Luxury 4K Tour','Walk through India''s most expensive residential complex with 360° views, amenities showcase, and interior finishes.','https://videos.pexels.com/video-files/3209828/3209828-hd_1920_1080_25fps.mp4','https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=450&fit=crop','4:32',24500,'luxury-tour',true,'Jun 20, 2026'),
(2,'🌳 Sobha Aranya – Nature-Inspired Living','Tour the eco-friendly, nature-centric residential community with landscaped gardens, walking trails, and luxury amenities.','https://videos.pexels.com/video-files/2911996/2911996-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=450&fit=crop','3:45',18200,'lifestyle',true,'Jun 18, 2026'),
(3,'🎨 Smart World The Edition – Japanese Design','Explore the Japanese-inspired minimalist architecture, serene interiors, and unique design elements of The Edition.','https://videos.pexels.com/video-files/7710243/7710243-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=450&fit=crop','5:18',14700,'design',false,'Jun 15, 2026'),
(4,'🏙️ Emaar Urban Ascent – Dubai-Style Living','Experience the premium lifestyle of Emaar Urban Ascent on Dwarka Expressway with world-class amenities and contemporary design.','https://videos.pexels.com/video-files/4248199/4248199-hd_1920_1080_25fps.mp4','https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=450&fit=crop','3:52',12600,'premium',true,'Jun 12, 2026'),
(5,'💎 Central Park Delphine – Resort Living','Discover resort-style luxury with infinity pools, private courtyards, and 5-star amenities in Central Park Delphine.','https://videos.pexels.com/video-files/3129671/3129671-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=450&fit=crop','4:10',16800,'luxury-tour',true,'Jun 10, 2026'),
(6,'🎯 PropertyInsta 3D Property Showcase','Experience the future of real estate with our 3D architectural visualization tool. Rotate, explore, and get AI-powered insights.','https://videos.pexels.com/video-files/3127273/3127273-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&h=450&fit=crop','2:28',8900,'platform',false,'Jun 8, 2026'),
(7,'🌃 Godrej Aristocrat – Premium Golf Course Living','Tour one of Golf Course Extension''s most coveted addresses with premium finishes and exclusive amenities.','https://videos.pexels.com/video-files/1788310/1788310-hd_1920_1080_24fps.mp4','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=450&fit=crop','3:34',11400,'luxury-tour',false,'Jun 5, 2026'),
(8,'🎬 PropertyInsta Guided Property Tours','Meet Aarav, your AI guide. Watch him narrate immersive property tours with automated scene transitions and voice narration.','https://videos.pexels.com/video-files/3129671/3129671-hd_1920_1080_30fps.mp4','https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=450&fit=crop','3:15',7600,'platform',false,'Jun 3, 2026')
ON CONFLICT (id) DO NOTHING;

-- Keep identity sequences ahead of the seeded ids so future inserts don't clash
SELECT setval(pg_get_serial_sequence('public.blogs','id'),    COALESCE((SELECT MAX(id) FROM public.blogs), 1));
SELECT setval(pg_get_serial_sequence('public.podcasts','id'), COALESCE((SELECT MAX(id) FROM public.podcasts), 1));
SELECT setval(pg_get_serial_sequence('public.videos','id'),   COALESCE((SELECT MAX(id) FROM public.videos), 1));
